codename: cifar10-simclr-96-lars-warmup-ddp-example
seed: -1
num_iters: 26042
log_dir: logs
checkpoint_dir: checkpoints

hid_dim: 2048
out_dim: 128
temp: 0.5

dataset: cifar10
dataset_dir: dataset
crop_size: 32
crop_scale_range:
  - 0.8
  - 1
hflip_prob: 0.5
distort_strength: 0.5
#gauss_ker_scale: 10
#gauss_sigma_range:
#  - 0.1
#  - 2
#gauss_prob: 0.5

batch_size: 96
num_workers: 2

optim: lars
lr: 0.5
momentum: 0.9
#betas:
#  - 0.9
#  - 0.999
weight_decay: 1.0e-06

sched: warmup-anneal
warmup_iters: 2604