codename: 'cifar10-resnet50-256-lars-warmup'
seed: -1

dataset_dir: 'dataset'
dataset: 'cifar10'
crop_size: 32
crop_scale_range: '0.8-1'
hflip_p: 0.5
distort_s: 0.5
gaussian_ker_scale: 10
gaussian_sigma_range: '0.1-2'
gaussian_p: 0.5

batch_size: 256
restore_epoch: 0
n_epochs: 1000
warmup_epochs: 10
n_workers: 2
optim: 'lars'
sched: 'warmup-anneal'
lr: 1.
momentum: 0.9
weight_decay: 1.0e-06

log_dir: 'logs'
tensorboard_dir: 'runs'
checkpoint_dir: 'checkpoints'