codename: cifar10-vit-adam-warmup-anneal
seed: -1
num_iters: 1000
log_dir: logs
checkpoint_dir: checkpoints

backbone: vit
label_smooth: 0.1

dataset: cifar10
dataset_dir: dataset
crop_size: 32
crop_scale_range:
  - 0.8
  - 1
hflip_prob: 0.5

batch_size: 256
num_workers: 2

optim: adam
lr: 0.001
betas:
  - 0.9
  - 0.999
weight_decay: 5.0e-05

sched: warmup-anneal
warmup_iters: 5